/*
 * Copyright (C) 2016 Hedede <haddayn@gmail.com>
 *
 * License LGPLv3 or later:
 * GNU Lesser GPL version 3 <http://gnu.org/licenses/lgpl-3.0.html>
 * This is free software: you are free to change and redistribute it.
 * There is NO WARRANTY, to the extent permitted by law.
 */
TOKEN(illegal)
TOKEN(eof)
TOKEN(identifier)
TOKEN(numeric_constant)
TOKEN(string_literal)
TOKEN(comment)

PUNCT(comma,            ",")
PUNCT(dot,              ".")
PUNCT(semicolon,        ";")
PUNCT(l_brace,          "{")
PUNCT(r_brace,          "}")
PUNCT(l_bracket,        "[")
PUNCT(r_bracket,        "]")
PUNCT(l_paren,          "(")
PUNCT(r_paren,          ")")
PUNCT(amp,              "&")
PUNCT(amp_amp,          "&&")
PUNCT(pipe,             "|")
PUNCT(pipe_pipe,        "||")
PUNCT(ast,              "*")
PUNCT(ast_equal,        "*=")
PUNCT(plus,	        "+")
PUNCT(plus_equal,       "+=")
PUNCT(plus_plus,        "++")
PUNCT(minus,	        "-")
PUNCT(minus_equal,      "-=")
PUNCT(minus_minus,      "--")
PUNCT(slash,	        "/")
PUNCT(slash_equal,      "/=")
PUNCT(percent,	        "%")
PUNCT(less,	        "<")
PUNCT(less_equal,       "<=")
PUNCT(less_less,        "<<")
PUNCT(greater,          ">")
PUNCT(greater_equal,    ">=")
PUNCT(greater_greater,  ">>")
PUNCT(bang,             "!")
PUNCT(bang_equal,       "!=")
PUNCT(tilde,            "~")
PUNCT(caret,            "^")
PUNCT(equal,            "=")
PUNCT(equal_equal,      "==")

TOKEN(keyword)
KEYWORD(const)
KEYWORD(var)
KEYWORD(func)
KEYWORD(if)
KEYWORD(else)
KEYWORD(class)
KEYWORD(prototype)
KEYWORD(instance)
KEYWORD(return)
KEYWORD(void)
KEYWORD(float)
KEYWORD(int)
KEYWORD(string)

// extensions
KEYWORD(extern)
KEYWORD(while)
KEYWORD(do)
